{% set version = "0.12.0" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/featuretools/featuretools-{{ version }}.tar.gz
  sha256: 699d2f2eff4e49a84ce1b4396b2a68bf593d369cf976bca2d7b70ea2b2ed4c1a

build:
  entry_points:
    - featuretools = featuretools.__main__:cli
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
  run:
    - click >=7.0.0
    - cloudpickle >=0.4.0
    - dask >=1.1.0
    - distributed >=1.24.2
    - funcsigs >=1.0.2  # remove when we drop python2
    - future >=0.16.0
    - numpy >=1.13.3
    - pathlib >=1.0.1
    - pandas >=0.23.*
    - psutil >=5.4.8
    - python
    - pyyaml >=3.12
    - scikit-learn >=0.20.0
    - smart_open >=1.8.4
    - s3fs >=0.2.2
    - tqdm >=4.32.0

test:
  commands:
    - featuretools --help
    - featuretools info
    - featuretools list-primitives
    - pytest --doctest-modules featuretools/
  imports:
    - featuretools
  requires:
    - fastparquet >=0.1.6
    - moto >=1.3.13
    - pympler >=0.5,<0.6
    - pytest >=4.1.*,<4.2
    - pytest-xdist >=1.26.1
    - python-graphviz >=0.8.4
  source_files:
    - featuretools/*

about:
  doc_url: https://docs.featuretools.com
  dev_url: https://github.com/Featuretools/featuretools/
  home: https://featuretools.com
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'a framework for automated feature engineering'

extra:
  recipe-maintainers:
    - kmax12
    - rwedge
